### ISSUE TITLE
License information for the QuirkyPSFunctions

### ISSUE THREAD

**Issue by SveinSoerenson** [weloytty/QuirkyPSFunctions#2]
Dear weloytty,

I would like to use some of your PowerShell scripts, but I did not find any license information.
Under which license (MIT, GPL, ...) do you distribute your Software?

Thanks a lot,
Svein Soerenson

**Comment by weloytty** [comment]
Hi Svein,

I added the unlicense to the repo, it was the most permissive one I could find, does that work?

**Comment by SveinSoerenson** [comment]
Hi weloytty,

thank you very much. I see the file and it works. :-)
